### ISSUE TITLE
User can select comparison area from prior selections within session

### ISSUE THREAD

**Issue by EricaMaurer** [NYCPlanning/labs-factfinder#10]
only in "standard" and "change comparison" report view (without reliability)

**Comment by andycochran** [comment]
This could be done by porting over the "SAVE" feature we have in ZoLa. When you create a selection and generate a profile, you can save that profile in local storage (computer's cache). Then, when selecting from comparison area list, you can choose from your saved profiles.

**Comment by hannahkates** [comment]
No longer relevant.
