### ISSUE TITLE
Backup and delete labs-db Postgres database cluster

### ISSUE THREAD

**Issue by TylerMatteo** [NYCPlanning/labs-factfinder#1109]
We want to delete the `labs-db` postgresql cluster in digital ocean because it is running v11 which goes EoL soon and we no longer use this cluster. 

This cluster contains several databases related to earlier iterations of the ZAP Search and Applicant Portal projects. We believe these to no longer be in use but we want to create and download backups of them just in case.

## Steps
- [x]  Download backups of the following databases in the `labs-db` cluster

![Image](https://github.com/NYCPlanning/labs-factfinder/assets/9055367/fd48acec-f17e-4b06-a457-1cdd0fbc1b78)

- [x] Verify that you can restore from those backups by restoring them to a local postgres cluster
- [x] Upload the backups to DO Space `ae-data-backups` under the `zap` folder
- [x]  Delete the cluster by navigating to the settings for the cluster and selecting "Destroy" under "Destroy this database cluster"

**Comment by TangoYankee** [comment]
Waiting until Nov 02 to delete the cluster, giving folks a chance for last calls.
