### ISSUE TITLE
Issue/16067 PFF Updates: Add ACS Data for City Council Districts (CCDs)

### ISSUE THREAD

**Issue by horatiorosa** [NYCPlanning/labs-factfinder#1128]
### Ticket 
[Issue 16067](https://dev.azure.com/NYCPlanning/ITD/_workitems/edit/16067)
[Workflow branch strategy](https://github.com/NYCPlanning/labs-factfinder/issues/1134)
##### ADD 
   - [ ] Data for City Council Districts (CCDs)

**Comment by horatiorosa** [comment]
add acpept. crtiteria
you can load acs data for ccds

**Comment by horatiorosa** [comment]
Blocked until the data is ready, could be EOD 2/23/2024

**Comment by TylerMatteo** [comment]
@horatiorosa Switching out @TangoYankee for myself. See note on #1132
