### ISSUE TITLE
Issue/16067: PFF Updates: ACS—General: difference/change of 0 should be shown in grey 

### ISSUE THREAD

**Issue by horatiorosa** [NYCPlanning/labs-factfinder#1180]
### Description
Difference/change of 0 should be shown in grey (only happens sometimes on my end so not sure if it’s a true issue or not)

[Example here](https://factfinder-staging.planninglabs.nyc/explorer/selection/e4d62c2df957bc0bcbda8818476517585fb7f19b?acsTopics=%2Cdemo-mutuallyExclusiveRaceHispanicOrigin&compareTo=BK0103&showReliability=true&source=acs-current)

Previously reported here [ADO#5033](https://dev.azure.com/NYCPlanning/ITD/_workitems/edit/5033/)
#### Note
Make a branch from staging and merge all PR back into staging

**Comment by TylerMatteo** [comment]
I think we can disregard this one - it seems to still be happening only occasionally like described in the ADO Bug

**Comment by horatiorosa** [comment]
OK, Ill close this issue.
