### ISSUE TITLE
User can download individual variables from report view

### ISSUE THREAD

**Issue by EricaMaurer** [NYCPlanning/labs-factfinder#25]
Example: if a user only wants to download "language spoken at home" instead of the full database or social profile.

**Comment by allthesignals** [comment]
ogr2ogr throws error on csv download: 

```
    "ogr2ogr command return code 1, Error: ERROR 1: ERROR:  column reference \"acs_year\" is ambiguous\nLINE 1: ... SELECT \"sum\",\"m\",\"comparison_sum\",\"comparison_m\",\"acs_year\"...\n                                                             ^\n\n"
```

**Comment by allthesignals** [comment]
@chriswhong Carto tends to wrap the query which throw things off a bit... I'm not sure why the "__wrapped" subquery exists for the dataset viewer. I can't confirm whether or not the ogr2ogr csv conversion has the same behavior, but this looks very similar. 

![Screen Shot 2017-11-09 at 3.59.24 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5830e3bc40b5a00e00a5b4c0/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76226454fa6b7191a37bf117224f5d5b5ecc3c4a4356bcbbd671f3e57862804e0ee484650b76c26c13a4b0d64bbb01ba26df4a81b2bc8e45d2f42f67b6d5db1063474f4dcbed5727a29b41c95df74be34b54a51b3161ef732431.png)

**Comment by allthesignals** [comment]
![Screen Shot 2017-11-09 at 3.59.24 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5830e3bc40b5a00e00a5b4c0/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76226454fa6b7191a37bf117224f5d5b5ecc3c4a4356bcbbd671f3e57862804e0ee484650b76c26c13a4b0d64bbb01ba26df4a81b2bc8e45d2f42f67b6d5db1063474f4dcbed5727a29b41c95df74be34b54a717356ae2752431.png)

**Comment by EricaMaurer** [comment]
I can change it

**Comment by hannahkates** [comment]
No longer relevant
