### ISSUE TITLE
Uncaught TypeError: Cannot read property 'find' of undefined

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-factfinder#328]
#### What should happen:
Console is free of errors!

#### What happened instead:
`acs-table.js: Uncaught TypeError: Cannot read property 'find' of undefined`

#### How to reproduce this bug:

1. Scroll report view
2. Toggle reliability
3. Resize window

#### Browser(s) and Device(s) observed on:
Chrome, MacOS

**Comment by andycochran** [comment]
This is now `data-table.js`.

**Comment by andycochran** [comment]
Hmm… I can't reproduce this. Could this have worked itself out?

**Comment by allthesignals** [comment]
Not seeing this anymore
