### ISSUE TITLE
formatting doesn't copy from firefox

### ISSUE THREAD

**Issue by EricaMaurer** [NYCPlanning/labs-factfinder#359]
formatting works when copied over from chrome but not firefox

**Comment by andycochran** [comment]
https://support.mozilla.org/en-US/questions/1106918

**Comment by chriswhong** [comment]
Investigate whether this is possible in other browsers, explore options for meeting this need.

**Comment by EricaMaurer** [comment]
![Capture.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59dcc3086ccbe400142879ce/125516c66e82c728ace21e0d46cb958a379791accda5fd53b652fa912a5265296b51fa2e2881b17cbe1023590b0b4aac415e0b41f8fd892fafa42062c80d55b98e30063e937f03a6aa8318b500bf218f4687b2bb8a4dc4ea3d37aa.JPG)

**Comment by andycochran** [comment]
@EricaMaurer Can you try EDIT > Paste Special and choosing formatted text? Maybe we can figure out if it's not coping or not pasting.

**Comment by andycochran** [comment]
Are there any Firefox Extensions running?
