### ISSUE TITLE
Refactor Choropleth Data Access

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-factfinder#374]
All choropleths are shoved into one vector tile, so any tile request is extra complicated and gets data for choropleths that are not being used.

This is not sustainable, as adding new choropleths will add even more processing time to each tile request, and we are starting to see errors when these are requested.

The right thing to do is request non-spatial NTA data from carto when a given choropleth is turned on, and use it to generate a style for the existing NTA layer.

**Comment by andycochran** [comment]
Currently, there's no UI feedback that anything is happening when you turn on choropleths. Users will not wait for them to load; they'll assume something broke. Could we add a loading spinner to the map?

**Comment by allthesignals** [comment]
Is this still an issue? Closing for now, choropleth seem fast
