### ISSUE TITLE
Column formatting is lost when user changes zoom

### ISSUE THREAD

**Issue by EricaMaurer** [NYCPlanning/labs-factfinder#459]

**Comment by EricaMaurer** [comment]
100 percent zoom
![100pct.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59dcc3086ccbe400142879ce/125516c66e82c728ace21e0d46b9c4ca338197ebc3abaf51ab57f5973d047d317c5da67374d7b729ed1a23050b5b4eac470c5a40f8f98d22b4aa2e32db025fb28c341521842f1bbeb98a15be04bb268d4a87b1b98e45c4ed2f68.JPG)

**Comment by EricaMaurer** [comment]
80 percent zoom 
![80pct.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59dcc3086ccbe400142879ce/125516c66e82c728ace21e0d46b0c48a2096c1e5cdf9ad4cae58f3806b1c65267001fb2f22d1e27ae71a7f055b5f4eaa155d5b40fcfd8039baa47e21d40854b088270a36d43703adbf881eba00bc268e4d82b0bd824ec3fa70.JPG)

**Comment by EricaMaurer** [comment]
80 percent zoom
![80pct.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59dcc3086ccbe400142879ce/125516c66e82c728ace21e0d46b0c48a2096c1e5cdf9ad4cae58f3806b1c65267001fb2f22d1e27ae71a7f055b5f4eaa155d5b40fcfd8039baa47e21d40854b088270a36d43703aeb8881eba00bc268e4d82bebb8d45c0fa70.JPG)

**Comment by hannahkates** [comment]
I'm not seeing this in Chrome. Is it a browser issue?

**Comment by EricaMaurer** [comment]
@hannahkates I'm not sure. This was from a year ago and haven't heard this complaint since. Closing -- no longer relevant.
