### ISSUE TITLE
Highlighted geometries are clipped to tile boundary

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-factfinder#51]
To highlight on mousemove, we `queryRenderedFeatures()`and get the geometry of the feature that is under the mouse pointer.  This is clipped to the tile boundary, however, and often shows only a partial geometry.

This issue on mapbox-gl-js presents a workaround that uses `querySourceFeatures()` to get the complete geometry.  We should get this working, and apply the same fix to ZoLa.

https://github.com/mapbox/mapbox-gl-js/issues/3871

<img width="1094" alt="fullscreen_10_27_17__9_48_am" src="https://user-images.githubusercontent.com/1833820/32107234-ff295e42-bafb-11e7-8ec7-518ace0bd201.png">

**Comment by chriswhong** [comment]
Went down a rabbithole on this...  tiles have a buffer so querying source features results in overlapping "chunks".  I documented it [here](https://github.com/mapbox/mapbox-gl-js/issues/3871), but tabling for now

**Comment by EricaMaurer** [comment]
This happens with highlighting and selection
![image](https://user-images.githubusercontent.com/32674674/36689245-da6b22b4-1afc-11e8-843a-ae7270e9ea73.png)

**Comment by hannahkates** [comment]
Closing because this will be fixed with the WIP integration of ember-mapbox-composer in PR #644
