### ISSUE TITLE
Have a sticky geography label and sticky reliability toggle on top so user can see selected geog/show reliability data while scrolling through profile

### ISSUE THREAD

**Issue by EricaMaurer** [NYCPlanning/labs-factfinder#523]

**Comment by allthesignals** [comment]
How should this work for long lists of Census tracts? @EricaMaurer

**Comment by EricaMaurer** [comment]
@allthesignals collapse the list-- only show the first few with an ellipsis at the end?

**Comment by EricaMaurer** [comment]
Reopening. Should have discussions on the sticky label for the selected area. In the meantime, "Your Selection Area" should still be shown as "Selected Area"

**Comment by allthesignals** [comment]
Closed by #526b068
