### ISSUE TITLE
"The drop-down arrow for the jump to feature is not very prominant"

### ISSUE THREAD

**Issue by EricaMaurer** [NYCPlanning/labs-factfinder#563]
The drop-down arrow could be made larger or darker to address this.

![Screen Shot 2018-12-10 at 2.11.03 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/593ac159e983f40020992a93/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76216455f36b7191a37af1132a4f5f5c5ecc3c4a4356bcbbd671f3e57862804e0ee484650b76c26c13a4b0d64bbb01ba26df4a81b2bc8e45d2f42f67b6d5db1063474f4dcbed5727a19041c95df24fe54b5ca41b3762e5732431.png)

**Comment by allthesignals** [comment]
Is this still an issue?

**Comment by EricaMaurer** [comment]
Could be improved but not an actual issue.
