### ISSUE TITLE
User testing session: Need to discover commonalities and action items

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-factfinder#566]
Issue for user testing session that took place over the weekend. Issue is closed when we've identified commonalities and discovered action items from this feedback. The names below are not real and have been changed to protect the innocent ;) 

# Population Fact Finder User Testing:

## Bob

I asked him to find a statistic about tenure:
* First searched for ZIP Code
* Believes the search box is searching the summary level toggle items (searching for Census tract)
* Believes search box is related to summary level toggle
* Began twisting the map in many ways
* Manually looked for home
* Looked for advanced options
* Did not consider the non-significance of many of the statistics he was looking at
* Clicked back to map button the left to change selection
* Thought he needed to click control key to select multiple
* Doesn’t seem to notice the other tabs for other data…
* Confused by some of the ACS variable labels, summary level labels

I asked him to find the margin of error:
* He kept clicking the row itself for the reliability information

He wanted to find Jackson Heights:
* Wants to click field to find other contexts for that statistic
* Wants to sort of rank a particular statistic to see where it ranks
* Comparison area was not obvious
* Confused that the drawing tool unselected his currently-selected
* Forgot there was another selection outside of the map
* Once he found his selection area, he kept using the unreliable metrics, did not understand they were not-usable

## Jason

I asked him to find statistics about percent working-age:
* Clicked neighborhood directly to find LES where he lives
* Asked “why is it negative”, referring to the “difference” column
* “Comparison Area” column name is too vague

I asked him to fine-tune his geography:
* As he was toggling, he was surprised by losing some of his work at different levels

## Stacy

I asked her to find data about housing in her neighborhood:
* Started by drawing, surprised her shape was too sensitive for the selection
* Surprised selected things didn’t match what she drew
* Wanted a preview of what the selection might be
* Clicked advanced options, then thematic maps, didn’t know it was supportive data
* Clicked View Profile button, was confused by row color 
* Wanted to sort and highlight relevant information
* Wanted the ability to edit down which variables are visible

## Lee

I asked him to find mean commute time to work:
* Clicked draw
* Clicked advanced
* Went to economic first and found it immediately

## James

I asked him to find economic statistics:

* Starts with search, geocodes a dot
* Believes that’s all he needs to do, thought the dot was going to find data
* Wasn’t familiar with what census tract and block means, wanted tooltips to explain
* Thinks the dot is already tagging a summary area
* Went from dot to draw (instead of clicking) the census tract
* Very distracting interaction with the draw mode
* Wants to find Harlem to compare his area to
* Not sure what the graying means
* Wants to search for a specific statistic in-app
* Did find the contrast in table intuitive
* Wanted to find a table of contents, didn’t see the dropdown of TOC
* 	Suggestion: Trigger dropdown TOC on mouseover of whole tab
* Profile toggle doesn’t have enough contrast 
* 	Suggestion: A bigger label asking what the user wants
* Wanted to sort some of the columns

Direct feedback:
* The map selection step could use some walk-through and more guidance
* Thought searching the dot was enough and “ready to go” but it wasn’t 
* 	Suggestion: maybe it will default select the intersecting tract
* Drawing could use some better walk-through and guidance
* Thematic maps seem buried - maybe specific rows could link back from the table
* Thought “thematic maps” was too technical of a term
* Found the cream row confusing, maybe bold it instead to indicate that it’s a total
* Any action that pertains to the data should be contained around it
* The row highlight select should only select one at a time
* Blue doesn’t really convey the right thing, maybe use cream (after replacing cream highlighting with bold)
* Not clear how to end drawing state
* Confusing why the app begins on Census tract toggle in map selection mode
* Maybe have some visual icons sequencing the spatial relationship

**Comment by hannahkates** [comment]
No longer relevant
