### ISSUE TITLE
Fix CSV download column order, row order, remove old years, conditional columns, rename variables

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-factfinder#567]
we should use the previous columns instead of find the row through nesting - it is only used in one place

**Comment by EricaMaurer** [comment]
previous_m, previous_cv, and previous_percent_m are not in the download

**Comment by EricaMaurer** [comment]
Census download currently does not work-- so do not what the labels are to determine columns to include.

ACS Profiles (current and change views): 
1. remove "not in profile" variables
2. remove "2006_2010" rows
3. reliability and significant columns displayed as TRUE/FALSE

Order of columns for each view in attached file
[Decennial and ACS Profile CSV Column Order.xlsx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59dcc3086ccbe400142879ce/125516c66e82c728ace21e0d46cc9199268c8da08ee5ff42aa59b0b50a7567433b0ba5227c80a30b8c743b2200030bf11f482006a8accb39baa47c32d5065ebe957f5566c33444a4ec801bee03b228df1b81b6bc8c18c5ec3925e3829d532c5c5446dda0006ceacc09da52e449e04754a111346be3733779439d16723e26.xlsx)

**Comment by allthesignals** [comment]
Decennial download seems to be working @EricaMaurer

**Comment by EricaMaurer** [comment]
Updated:

ACS Profiles (current and change views):

remove "not in profile" variables
remove "2006_2010" rows
reliability and significant columns displayed as TRUE/FALSE
Order of columns for each view in attached file
*the change and difference columns are flagged for significance but we are testing for reliability-- can we change the column label?*

Decennial Profiles (current and change views):

remove "not in profile" variables
remove "2000" rows
remove reliability and significant columns
Order of columns for each view in attached file

[Decennial and ACS Profile CSV Column Order.xlsx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59dcc3086ccbe400142879ce/125516c66e82c728ace21e0d46cc9199268c8da08ee5ff42aa59b0b50a7567433b0ba5227c80a30b8c743b2200030bf11f482006a8accb39baa47c32d5065ebe957f5566c33444a4ec801bee03b228df1b81b6bc8c18c5ec3925e3829d532c5c5446dda0006ceacc09da52e449e24754a1173267e17632744f911b703e26.xlsx)

**Comment by allthesignals** [comment]
@EricaMaurer can you enumerate some of the lingering issues on this? Also @trbmcginnis can meet with you on this.

**Comment by trbmcginnis** [comment]
Additional changes:
- Edit the API and the front end, change names of variables to be clearer
- reorder category rows--group similar rows
