### ISSUE TITLE
User feedback on search bar

### ISSUE THREAD

**Issue by EricaMaurer** [NYCPlanning/labs-factfinder#579]
"I thought the categories indicated below the search box (i.e. census block, census tract, NTA, and PUMA) were the search options.  How about placing in search box “Search by address…”"

People also seem to be using this to search for variables.

"Would be great if the search bar allowed you to outline any geography listed in the overlay options... like Community Districts"

**Comment by trbmcginnis** [comment]
User can search by subway line and station
