### ISSUE TITLE
Upgrade ember-decorators

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-factfinder#598]

**Comment by chriswhong** [comment]
Upgrading ember-decorators will require changing every instance of `@computed` throughout the app.

**Comment by allthesignals** [comment]
Do you mean how it is imported? Actually, we will also have to upgrade to class syntax because decorators on “methods” of object literals is no longer valid (the decorators spec changed slightly, it’s almost finalized now though).

**Comment by allthesignals** [comment]
So yes we would need to change a lot to upgrade ember decorators, and we probably should anyways
