### ISSUE TITLE
Update inflation factor for 06-10 data

### ISSUE THREAD

**Issue by EricaMaurer** [NYCPlanning/labs-factfinder#653]
https://github.com/NYCPlanning/labs-factfinder-api/blob/251a30d0484d417f7d76d24fedeb1fc3dbdeffbd/utils/inflate.js 

Inflates 2010 dollars to 2017 dollars

Change inflation from 1.1005 to 1.1267

**Comment by allthesignals** [comment]
Closed by NYCPlanning/labs-factfinder-api#51
