### ISSUE TITLE
Add new section at the end of the Social Profile

### ISSUE THREAD

**Issue by EricaMaurer** [NYCPlanning/labs-factfinder#654]
Section name: Computers and Internet Use
Total households (HH3) -- base
With a computer (HHComp)
With a broadband Internet subscription (HHInt)

does not appear in 2006-2010 data.

**Comment by allthesignals** [comment]
@EricaMaurer this is ready to look at on staging: https://factfinder-staging.planninglabs.nyc/profile/705/social

I'm not sure if the numbers for computer use are right... I'm guessing they are since I assume they overlap. Let me know if anything looks off thanks.
