### ISSUE TITLE
Update 06-10 top- and bottom-coding shown for aggregated geogs

### ISSUE THREAD

**Issue by EricaMaurer** [NYCPlanning/labs-factfinder#657]
Economic: 
MdHHInc : top-coding: 200,000 inflated to 225,340 displayed as 225,000
bottom-coding: 9,999 inflated to 11,266 displayed as 11,000

MdFamInc : top-coding: 200,000 inflated to 225,340 displayed as 225,000
bottom-coding: 9,999 inflated to 11,266 displayed as 11,000

MdNFInc : top-coding: 200,000 inflated to 225,340 displayed as 225,000
bottom-coding: 9,999 inflated to 11,266 displayed as 11,000

MdEWrk : top-coding: 100,000 inflated to 112,670 displayed as 112,500
bottom-coding: 2,499 inflated to 2,816 displayed as 2,800

MdEMFTWrk: top-coding: 100,000 inflated to 112,670 displayed as 112,500
bottom-coding: 2,499 inflated to 2,816 displayed as 2,800

MdEFFTWrk: top-coding: 100,000 inflated to 112,670 displayed as 112,500
bottom-coding: 2,499 inflated to 2,816 displayed as 2,800

Housing:
MdVl: top-coding: 1,000,000 inflated to 1,276,700 displayed as 1,275,000

MdGR: top-coding: 2,000 inflated to 2,253 displayed as 2,250

**Comment by hannahkates** [comment]
This needs to be addressed in the API.

**Comment by allthesignals** [comment]
I just merged this here: https://github.com/NYCPlanning/labs-factfinder-api/pull/52. Once we get staging pipeline setup and going, @JoelAAlvarez can review

**Comment by allthesignals** [comment]
This can be reviewed here: https://deploy-preview-690--labs-factfinder.netlify.com/
