### ISSUE TITLE
Margin of error exceeds 100% in charts

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-factfinder#685]
We see charts that go beyond 100% (both the x-axis and MOEs go beyond, in certain instances…we added red bars to an example below, to illustrate)
![image](https://user-images.githubusercontent.com/13967925/52565113-e4b61b80-2dd3-11e9-9e46-0b06fb99f75a.png)

**Comment by trbmcginnis** [comment]
Example: https://factfinder-staging.planninglabs.nyc/profile/1345/social?comparator=SI22

**Comment by trbmcginnis** [comment]
![120.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b1a8ed004e6dd00118290e2/125516c66e82c728ace21e0d46b9c6ca61cec1b99de6b546a749b2ce6b137e767100f17f71d7bb70bb462f515f591aa9455c5f40f5eb9539e4e76224d50152a7842f4d7ed43c19a6b9871bb608b8208d4a85b3b9825e8d.png)
