### ISSUE TITLE
Decennial: homeowner vacancy rate and rental vacancy rate

### ISSUE THREAD

**Issue by EricaMaurer** [NYCPlanning/labs-factfinder#742]
Data are not accurately appearing in the application. Possible fix is that the calculations are missing to piece to be multiplied by 100.

![image](https://user-images.githubusercontent.com/32674674/73957081-d827ae80-48d3-11ea-8e1c-b83a3703a0ae.png)
https://popfactfinder.planning.nyc.gov/profile/802/census

**Comment by allthesignals** [comment]
Does this issue prevent the new ACS data release? It seems like it's happening on production.

**Comment by allthesignals** [comment]
Okay, when I multiply the rate by 100, I get the follow data for the variable:

```
id: "SG1Pd25yVmNSdA==",
sum: 2.8832683294351167,
variable: "hmownrvcrt",
variablename: "HmOwnrVcRt",
base: "ratio",
category: "housing_occupancy",
profile: "decennial",
percent: null,
percent_m: null,
previous_sum: 1.6816467291734023,
previous_percent: null,
comparison_sum: 2.88326832943512,
comparison_percent: null,
change_sum: 1.2016216002617144,
change_percent: 0.7145505529882369,
change_percentage_point: null,
change_percentage_point_m: null,
difference_sum: -3.1086244689504383e-15,
significant: true,
difference_percent: 0
```

However, I'm concerned that this will affect downstream calculations that depend on it... there is one variable that reference this as its base, and this is what it computes to:

```
id: "T09jSFUx",
sum: 962892,
variable: "oochu1",
variablename: "OOcHU1",
base: "HmOwnrVcRt",
category: "housing_occupancy",
profile: "decennial",
percent: 0,
previous_sum: 912296,
previous_percent: 0,
comparison_sum: 962892,
comparison_percent: 0,
change_sum: 50596,
change_percent: 0.05546006997728807,
change_percentage_point: 0,
difference_sum: 0,
significant: true,
difference_percent: 0
```

If multiplying the sum_ratio (rate) by 100 does _not_ affect dependent variables, then it seems like it's not a problem... if it does, then we need to distinguish this mutliplication as a presentational factor...

**Comment by EricaMaurer** [comment]
this doesn't prevent the new ACS data from being released since it's an issue with decennial (and it's currently happening in production) but should be fixed. The rates are not an input into other variables, so fixing them shouldn't affect any other variables. oochu1 is an input into hmownrvcrt rather than the other way around.

**Comment by EricaMaurer** [comment]
was this pushed to staging already?

**Comment by allthesignals** [comment]
@EricaMaurer hmm it wasn't, let me see, I'll put up a PR.

**Comment by allthesignals** [comment]
https://github.com/NYCPlanning/labs-factfinder-api/pull/97 

I'm going to merge this because it sounds like it wouldn't affect downstream things.

It is something we want to think about though — multiply-by-100 for presentation can't always be used as inputs for other things, unless it's adjusted for.

**Comment by allthesignals** [comment]
Deploying now. @EricaMaurer please give this a look in a few minutes and see if it solves this specific problem. If it does, i'll close. Other observered side effects can be made into new issues. 

Thanks!

**Comment by EricaMaurer** [comment]
Solved this problem! thanks!!

**Comment by allthesignals** [comment]
Great! Closing for now. Keep eyes peeled for side-effects. Thank you!!!
