### ISSUE TITLE
Rename variables to be clearer

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-factfinder#756]
@allthesignals commented on [Thu Feb 21 2019](https://github.com/NYCPlanning/labs-factfinder-api/issues/56)

@trbmcginnis did a lot of research and found we should rename variables for the Row model. Things like "m", margin of error, are confusing and should be improved. 

We should carve out maintenance time alongside other refactoring tasks to address this.

---

@trbmcginnis commented on [Thu Feb 21 2019](https://github.com/NYCPlanning/labs-factfinder-api/issues/56#issuecomment-466061482)

Started to make changes in branch `variable-name-changes`, leaving this for now (still needs a lot of work, currently has failing tests, need to add more tests, double check variables, etc.). Tabling this for now to get CSV download issue resolved, will  revisit during a bigger refactor.

**Comment by TylerMatteo** [comment]
Just happened to come across this. This is actually resolved by https://github.com/NYCPlanning/labs-factfinder/pull/905 - closing.
