### ISSUE TITLE
Census block profiles don't load

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-factfinder#771]
#### How to reproduce this bug:

1. Switch to census blocks as your geography level
2. Select a census block or multiple on the map
3. Click profiles
4. See that profile content doesn't load and loader keeps loading

![image.png](https://images.zenhubusercontent.com/5ca2425fd9fcf5278d7159e7/f2de54b6-22bc-46a6-a0db-c4a40e91b88d)

**Comment by rtblair** [comment]
Fixed by https://github.com/NYCPlanning/labs-factfinder-api/pull/105
